clc;
clear all;
close all;

% Plotting script for the simulation in Section V.B.
% Run Sim_IV_B.m before executing this file.

% Load simulation results generated by Sim_IV_B.m
load myworkspace_IV_B.mat

% Align the generated switching input with the simulation time vector
Uplot = U(delaySteps+1 : delaySteps+numSteps+1);

fig = figure('Color','w','Units','inches','Position',[1,1,6.6,4.8]);

tl = tiledlayout(fig,2,1,'TileSpacing','compact','Padding','compact');

% State trajectories
ax1 = nexttile(tl,1);

plot(time,X(1,:),'r-','LineWidth',2.2);
hold on;
plot(time,X(2,:),'b-','LineWidth',2.2);

yline(0,'k:','LineWidth',0.8,'HandleVisibility','off');

grid on;
box on;

ylabel('$X(t)$','Interpreter','latex','FontSize',17);

legend('$X_1(t)$','$X_2(t)$','Interpreter','latex','FontSize',13,'Location','northeast','Box','off');

xlim([time(1),time(end)]);

set(ax1,'FontSize',14,'LineWidth',1.0,'TickDir','out','TickLabelInterpreter','latex','GridAlpha',0.18);

% Switching input
ax2 = nexttile(tl,2);

stairs(time,Uplot,'k-','LineWidth',2.0);

grid on;
box on;

yticks([1 2]);
ylim([0.75 2.25]);

xlabel('$t~[\mathrm{s}]$','Interpreter','latex','FontSize',17);
ylabel('$U(t)$','Interpreter','latex','FontSize',17);

xlim([time(1),time(end)]);

set(ax2,'FontSize',14,'LineWidth',1.0,'TickDir','out','TickLabelInterpreter','latex','GridAlpha',0.18);

linkaxes([ax1,ax2],'x');
